# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgETGFh2gAo8GZSwUV5gUAVRl_yuCopD
"""

from IPython.display import HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
    <title>Quick Styler</title>
    <style>
        body {
            background-color: #f4f4f4;
            text-align: center;
            font-family: Arial, sans-serif;
        }
        h1 {
            color: darkblue;
        }
        button {
            padding: 10px 20px;
            background-color: orange;
            border: none;
            border-radius: 8px;
            cursor: pointer;
        }
        button:hover {
            background-color: red;
            color: white;
        }
    </style>
</head>
<body>
    <h1>Quick Styler</h1>
    <p>Edit styles and see instant preview!</p>
    <button>Click Me</button>
</body>
</html>
"""

HTML(html_code)

html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Quick Styler</title>
</head>
<body>
    <h2>Hello from Google Colab!</h2>
</body>
</html>
"""

with open("quickstyler.html", "w") as f:
    f.write(html_content)

print("File created successfully!")

from IPython.display import display, HTML

display(HTML("""
<textarea id="cssInput" rows="6" cols="50">
body { background-color: lightblue; }
h1 { color: red; }
</textarea>
<br>
<button onclick="applyStyle()">Apply Style</button>

<h1>Live Preview</h1>

<script>
function applyStyle() {
    var css = document.getElementById("cssInput").value;
    var style = document.getElementById("dynamicStyle");
    if (!style) {
        style = document.createElement("style");
        style.id = "dynamicStyle";
        document.head.appendChild(style);
    }
    style.innerHTML = css;
}
</script>
"""))

from IPython.display import HTML

html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Mini QuickStyler</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            display: flex;
            height: 100vh;
        }

        .editor {
            width: 40%;
            background: #1e1e1e;
            color: white;
            padding: 15px;
            box-sizing: border-box;
        }

        textarea {
            width: 100%;
            height: 200px;
            margin-bottom: 10px;
            background: #2d2d2d;
            color: #00ffcc;
            border: none;
            padding: 10px;
            resize: none;
        }

        button {
            padding: 10px;
            width: 100%;
            border: none;
            background: #00bcd4;
            color: white;
            font-weight: bold;
            cursor: pointer;
        }

        button:hover {
            background: #0097a7;
        }

        .preview {
            width: 60%;
            background: #f4f4f4;
            padding: 20px;
            box-sizing: border-box;
        }
    </style>
</head>

<body>

<div class="editor">
    <h2>Mini QuickStyler</h2>

    <label>HTML Code:</label>
    <textarea id="htmlCode">
<h1>Hello Shakthi 🚀</h1>
<p>Edit this HTML and CSS live!</p>
<button>Click Me</button>
    </textarea>

    <label>CSS Code:</label>
    <textarea id="cssCode">
body {
    background-color: lightyellow;
    text-align: center;
}
h1 {
    color: red;
}
button {
    padding: 10px 20px;
    background: orange;
    border: none;
    border-radius: 8px;
}
    </textarea>

    <button onclick="updatePreview()">Run / Apply</button>
</div>

<div class="preview">
    <iframe id="previewFrame" style="width:100%; height:100%; border:none;"></iframe>
</div>

<script>
function updatePreview() {
    var html = document.getElementById("htmlCode").value;
    var css = "<style>" + document.getElementById("cssCode").value + "</style>";

    var previewFrame = document.getElementById("previewFrame");
    var preview = previewFrame.contentDocument || previewFrame.contentWindow.document;

    preview.open();
    preview.write(css + html);
    preview.close();
}

updatePreview(); // Auto run on load
</script>

</body>
</html>
"""

HTML(html_content)

from IPython.display import HTML

html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Shakthi Sivakumar | Portfolio</title>

<style>
*{
    margin:0;
    padding:0;
    box-sizing:border-box;
    font-family: 'Segoe UI', sans-serif;
}

body{
    background:#0f172a;
    color:white;
    line-height:1.6;
}

header{
    height:100vh;
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
    text-align:center;
    background:linear-gradient(135deg,#1e3a8a,#0f172a);
}

header h1{
    font-size:3rem;
}

header span{
    color:#38bdf8;
}

header p{
    margin-top:15px;
    max-width:500px;
}

.btn{
    margin-top:20px;
    padding:10px 20px;
    background:#38bdf8;
    border:none;
    border-radius:25px;
    color:#0f172a;
    font-weight:bold;
    cursor:pointer;
}

section{
    padding:60px 10%;
}

h2{
    margin-bottom:20px;
    color:#38bdf8;
}

.cards{
    display:grid;
    grid-template-columns:repeat(auto-fit,minmax(250px,1fr));
    gap:20px;
}

.card{
    background:#1e293b;
    padding:20px;
    border-radius:15px;
    transition:0.3s;
}

.card:hover{
    transform:translateY(-5px);
    background:#334155;
}

footer{
    text-align:center;
    padding:20px;
    background:#1e293b;
    margin-top:40px;
}
</style>
</head>

<body>

<header>
    <h1>Hi, I'm <span>Shakthi Sivakumar</span></h1>
    <p>Tech Enthusiast | AI & Cybersecurity Learner | Quiz Competitor | Creative Developer</p>
    <button class="btn" onclick="scrollToSection()">View My Work</button>
</header>

<section id="about">
    <h2>About Me</h2>
    <p>
        I'm a passionate technology student from Chennai who loves Artificial Intelligence,
        Cyber Security, Networking, and creative prompt engineering. I actively participate in
        tech quizzes and competitions to sharpen my skills.
    </p>
</section>

<section>
    <h2>Skills</h2>
    <div class="cards">
        <div class="card">Python</div>
        <div class="card">C Programming</div>
        <div class="card">Machine Learning Basics</div>
        <div class="card">Cyber Security Concepts</div>
        <div class="card">Networking</div>
        <div class="card">Prompt Engineering</div>
    </div>
</section>

<section>
    <h2>Projects</h2>
    <div class="cards">
        <div class="card">
            <h3>AI Image Prompt Tool</h3>
            <p>Created unique AI prompts for modern India themed competition.</p>
        </div>
        <div class="card">
            <h3>Mini QuickStyler</h3>
            <p>Built a live HTML + CSS editor using JavaScript.</p>
        }
        <div class="card">
            <h3>Cyber Security Quiz Prep</h3>
            <p>Designed tough MCQs covering OS, DBMS, Cloud & Networking.</p>
        </div>
    </div>
</section>

<section>
    <h2>Contact</h2>
    <p>Email: shakthi@example.com</p>
    <p>LinkedIn: linkedin.com/in/shakthi</p>
    <p>GitHub: github.com/shakthi</p>
</section>

<footer>
    © 2026 Shakthi Sivakumar | Built with ❤️
</footer>

<script>
function scrollToSection(){
    document.getElementById("about").scrollIntoView({behavior:"smooth"});
}
</script>

</body>
</html>
"""

HTML(html_content)

